include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
# - graphql-schema_comparator
# - minitest-profile
# - minitest-rails
# - minitest-reporters
domains: []
reporters:
- rubocop
- require_not_found
max_files: 0