#!/usr/bin/env ruby

require 'fileutils'

PLATFORM_DARWIN = "Darwin"
PLATFORM_LINUX = "Linux"
PLATFORM = `uname`.chomp

DEPENDENCIES = [ "git", "nano", "ruby-dev"]
GEMS = ["solargraph", "$HOME/.repos/dotfiles/customGems/debase-2.3.0.gem", "$HOME/.repos/dotfiles/customGems/ruby-debug-ide-2.3.0.gem"]

BASH_GIT_PROMPT_TEXT =
%{
  if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
    GIT_PROMPT_ONLY_IN_REPO=1
    source $HOME/.bash-git-prompt/gitprompt.sh
  fi
}

def system_or_exit1(*args)
    unless system(*args)
      puts "ERROR: Command failed. Aborting."
      exit 1
    end
    true
end

def has_cmd?(cmd)
    system("which #{cmd}", STDOUT => '/dev/null') == true
end
  
def install(cmd)
    if PLATFORM == PLATFORM_LINUX
      system_or_exit1("sudo apt-get -y install #{cmd}")
    elsif PLATFORM == PLATFORM_DARWIN
      system_or_exit1("brew install #{cmd}")
    else
      raise "Unsupported Platform: #{PLATFORM}"
    end
end

def install_gem(_gem)
    system_or_exit1("sudo gem install #{_gem}")
    system_or_exit1("gem install #{_gem}")
end

def install_git_prompt
  FileUtils.rm_rf("#{ENV['HOME']}/.bash-git-prompt")
  system_or_exit1("git clone https://github.com/magicmonty/bash-git-prompt.git #{ENV['HOME']}/.bash-git-prompt --depth=1")
end

def move_git_dot_files
  if File.exist?("#{ENV['HOME']}/.gitconfig")
    puts "WARN: Moving #{ENV['HOME']}/.gitconfig to #{ENV['HOME']}/.gitconfig.default"
    puts "      This file is load by the dotfile .gitconfig"
    FileUtils.mv("#{ENV['HOME']}/.gitconfig", "#{ENV['HOME']}/.gitconfig.default")
  end
  FileUtils.mv("#{ENV['HOME']}//.repos/dotfiles/.gitconfig", "#{ENV['HOME']}/.gitconfig")
  FileUtils.mv("#{ENV['HOME']}//.repos/dotfiles/.gitignore", "#{ENV['HOME']}/.gitignore")
end

def amend_bashrc
  bash_rc = "#{ENV['HOME']}/.bashrc"
  File.write(bash_rc, BASH_GIT_PROMPT_TEXT, mode: 'a')
end

def setup_vscode_files
  workspace = "/src/github.com/shopify/shopify"

  FileUtils.mv("#{ENV['HOME']}/.repos/dotfiles/launch.json", "#{workspace}/.vscode")
  FileUtils.mv("#{ENV['HOME']}/.repos/dotfiles/settings.json", "#{workspace}/.vscode")
  FileUtils.mv("#{ENV['HOME']}/.repos/dotfiles/.solargraph.yml", workspace)
  FileUtils.mv("#{ENV['HOME']}/.repos/dotfiles/debug", "#{workspace}/tmp")
end

puts "1. Cloning shelsen/dotfiles"
FileUtils.rm_rf("#{ENV['HOME']}/.repos")
system_or_exit1("mkdir -p $HOME/.repos")
system_or_exit1("git clone --recursive https://github.com/shelsen/dotfiles $HOME/.repos/dotfiles")

puts "2. Installing dependencies"
DEPENDENCIES.each do |app|
  unless has_cmd?(app)
    puts "Installing: #{app}"
    install(app)
  end
end

puts "3. Installing gems"
GEMS.each do |gem|
    puts "Installing Ruby Gem: #{gem}"
    install_gem(gem)
end

puts "4. Install bash-git-prompt"
install_git_prompt

puts "5. Copy over git dot files"
move_git_dot_files

puts "6. Amend bashrc"
amend_bashrc

puts "7. Copy over vscode files"
setup_vscode_files

puts "8. Refresh shell"
system_or_exit1("bash")